### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by zed-wong** [Uniswap/v3-subgraph#145]
Failed to build when running `yarn build`. I did run `yarn codegen` before. Any ideas?
```
yarn run v1.22.17
$ graph build
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping apiVersion from 0.0.4 to 0.0.5
  Skip migration: Bump mapping apiVersion from 0.0.5 to 0.0.6
  Skip migration: Bump manifest specVersion from 0.0.1 to 0.0.2
  Skip migration: Bump manifest specVersion from 0.0.2 to 0.0.4
✔ Apply migrations
✔ Load subgraph from subgraph.yaml
  Compile data source: Factory => build/Factory/Factory.wasm
⠋ Compile subgraphWARNING AS226: Expression resolves to unusual type 'usize'.

   let totalSupplyValue = null
                          ~~~~
 in src/utils/token.ts(67,26)

ERROR TS2322: Type '~lib/@graphprotocol/graph-ts/chain/ethereum/ethereum.CallResult<~lib/@graphprotocol/graph-ts/common/numbers/BigInt>' is not assignable to type 'i32'.

     totalSupplyValue = totalSupplyResult as i32
                        ~~~~~~~~~~~~~~~~~
 in src/utils/token.ts(70,24)

WARNING AS226: Expression resolves to unusual type 'usize'.

   let decimalValue = null
                      ~~~~
 in src/utils/token.ts(78,22)

✖ Failed to compile subgraph: Failed to compile data source mapping: 1 compile error(s)
Error: Failed to compile data source mapping: 1 compile error(s)
    at Compiler._compileDataSourceMapping (/home/whoami/dev/v3/graph/v3-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:307:13)
    at /home/whoami/dev/v3/graph/v3-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:216:20
    at updateInDeepMap (/home/whoami/dev/v3/graph/v3-subgraph/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/home/whoami/dev/v3/graph/v3-subgraph/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/home/whoami/dev/v3/graph/v3-subgraph/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/home/whoami/dev/v3/graph/v3-subgraph/node_modules/immutable/dist/immutable.js:1278:26)
    at /home/whoami/dev/v3/graph/v3-subgraph/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:215:24
    at /home/whoami/dev/v3/graph/v3-subgraph/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/home/whoami/dev/v3/graph/v3-subgraph/node_modules/immutable/dist/immutable.js:2206:13)
    at mappedSequence.__iterateUncached (/home/whoami/dev/v3/graph/v3-subgraph/node_modules/immutable/dist/immutable.js:3015:23)
UNCAUGHT EXCEPTION: Error: The AssemblyScript compiler crashed when compiling this file: 'src/mappings/factory.ts'
Suggestion: try to comment the whole file and uncomment it little by little while re-running the graph-cli until you isolate the line where the problem happens.
Also, please contact us so we can make the CLI better by handling errors like this. You can reach out in any of these links:
- Discord channel: https://discord.gg/eM8CA6WA9r
- Github issues: https://github.com/graphprotocol/graph-cli/issues
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
$ node -v
v18.2.0
$ yarn -v
1.22.17
$ graph -v
0.33.1
```
package.json:
  "devDependencies": {
    "@graphprotocol/graph-cli": "0.33.1",
    "@graphprotocol/graph-ts": "0.27.0",
    "@typescript-eslint/eslint-plugin": "^2.0.0",
    "@typescript-eslint/parser": "^2.0.0",
    "eslint": "^6.2.2",
    "eslint-config-prettier": "^6.1.0",
    "prettier": "^1.18.2",
    "typescript": "^3.5.2"
  }

**Comment by Ololosha100501** [comment]
Where was the problem?

**Comment by Jackluren** [comment]
How to solve this problem?
